### ISSUE TITLE
Request for takedown

### ISSUE THREAD

**Issue by CV35W** [python-nerd-3/Beatblock#1]
Hello! CV here from Bubbletabby. 
While we appreciate fanmade works inspired by our game, we would like to request that this particular instance be removed. Beatblock is still currently in development, and we'd prefer that it not be represented this way (several of our levels have assets that are mascots or characters created by the artists we collaborate with, and we want to ensure we don't misrepresent their work.) 
Additionally, please don't put irl photos of who we assume is either you or someone you know in the game files! Be careful with what you post online. You can check how to scrub sensitive data from a repo with this: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

Thank you, and take care.

**Comment by python-nerd-3** [comment]
I will take the repository down. I understand your concerns.
